// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBItiVrHViBUAJ2I8juMD1aK4C3Se8RteM',
    appId: '1:314093190469:web:8ace967232d2709f0e522c',
    messagingSenderId: '314093190469',
    projectId: 'saruche-ecommerce-food',
    authDomain: 'saruche-ecommerce-food.firebaseapp.com',
    storageBucket: 'saruche-ecommerce-food.appspot.com',
    measurementId: 'G-XNFNKS7B7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTwpZhgfz1e4F4sZPlUadgoT06krbHaRs',
    appId: '1:314093190469:android:16598e1267ebb8540e522c',
    messagingSenderId: '314093190469',
    projectId: 'saruche-ecommerce-food',
    storageBucket: 'saruche-ecommerce-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb_GwHKeCqKmWUbZ6i4P8EAqZoUmSHGyc',
    appId: '1:314093190469:ios:84939ca86a9693430e522c',
    messagingSenderId: '314093190469',
    projectId: 'saruche-ecommerce-food',
    storageBucket: 'saruche-ecommerce-food.appspot.com',
    iosBundleId: 'com.example.nibblesEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb_GwHKeCqKmWUbZ6i4P8EAqZoUmSHGyc',
    appId: '1:314093190469:ios:84939ca86a9693430e522c',
    messagingSenderId: '314093190469',
    projectId: 'saruche-ecommerce-food',
    storageBucket: 'saruche-ecommerce-food.appspot.com',
    iosBundleId: 'com.example.nibblesEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBItiVrHViBUAJ2I8juMD1aK4C3Se8RteM',
    appId: '1:314093190469:web:891b93668e8ae17a0e522c',
    messagingSenderId: '314093190469',
    projectId: 'saruche-ecommerce-food',
    authDomain: 'saruche-ecommerce-food.firebaseapp.com',
    storageBucket: 'saruche-ecommerce-food.appspot.com',
    measurementId: 'G-HEP4Y6QHEB',
  );
}
